# Generated by Django 5.0.4 on 2024-04-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_price_remove_sale_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.IntegerField()),
                ('unit_value', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sale',
            name='produtos',
            field=models.ManyToManyField(to='sales.product'),
        ),
    ]
