# Generated by Django 5.0.4 on 2024-04-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleproduct_sale_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
    ]
