# Generated by Django 3.2.6 on 2024-04-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='produtos',
            field=models.ManyToManyField(related_name='sales', to='sales.Product'),
        ),
    ]
